services:

  # =========================
  # INFRASTRUCTURE
  # =========================

  postgres:
    image: postgres:17
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  redis:
    image: redis:7
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ecommerce-network

  kafka:
    image: apache/kafka:4.3.1
    container_name: ecommerce-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka-data:/var/lib/kafka/data

    networks:
      - ecommerce-network


  # =========================
  # CONFIG SERVER
  # =========================

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - ecommerce-network


  # =========================
  # SERVICE DISCOVERY
  # =========================

  service-discovery:
    build: ./service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - ecommerce-network


  # =========================
  # AUTHENTICATION
  # =========================

  authentication-service:
    build: ./authentication-service
    container_name: authentication-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - service-discovery
      - config-server
    networks:
      - ecommerce-network


  # =========================
  # VENDOR
  # =========================

  vendor-service:
    build: ./vendor-service
    container_name: vendor-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - service-discovery
      - config-server
    networks:
      - ecommerce-network


  # =========================
  # PRODUCT
  # =========================

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - redis
      - service-discovery
      - config-server
    networks:
      - ecommerce-network


  # =========================
  # INVENTORY
  # =========================

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - redis
      - kafka
      - service-discovery
      - config-server
    networks:
      - ecommerce-network


  # =========================
  # CART
  # =========================

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - service-discovery
      - config-server
    networks:
      - ecommerce-network


  # =========================
  # ORDER
  # =========================

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8086:8086"
    depends_on:
      - postgres
      - kafka
      - service-discovery
      - config-server
    networks:
      - ecommerce-network


  # =========================
  # PAYMENT
  # =========================

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8087:8087"
    depends_on:
      - postgres
      - kafka
      - service-discovery
      - config-server
    networks:
      - ecommerce-network


  # =========================
  # NOTIFICATION
  # =========================

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      - kafka
      - service-discovery
      - config-server
    networks:
      - ecommerce-network


  # =========================
  # API GATEWAY
  # =========================

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8089:8089"
    depends_on:
      - service-discovery
      - config-server
    networks:
      - ecommerce-network


# =========================
# NETWORK
# =========================

networks:
  ecommerce-network:
    driver: bridge


# =========================
# VOLUMES
# =========================

volumes:
  postgres-data:
  redis-data:
  kafka-data: