spring.application.name=authentication-service

server.port=8081

# PostgreSQL
# Added 'options=-c timezone=UTC' to prevent the driver from sending 'Asia/Calcutta'
spring.datasource.url=jdbc:postgresql://postgres:5432/ecommerce_auth?options=-c%20timezone%3DUTC
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Explicitly tell Hibernate the dialect to avoid needing JDBC metadata fallback
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always