spring.application.name=inventory-service
server.port=8084

spring.datasource.url=jdbc:postgresql://postgres:5432/ecommerce_inventory?options=-c%20timezone%3DUTC
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=inventory-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties[spring.json.value.default.type]=com.ecommerce.inventory.dto.DomainEvent
spring.kafka.consumer.properties[spring.json.trusted.packages]=com.ecommerce.inventory.dto
spring.kafka.consumer.properties[spring.json.use.type.headers]=false

spring.data.redis.host=redis
spring.data.redis.port=6379