spring.application.name=cart-service
server.port=8085

spring.data.redis.host=redis
spring.data.redis.port=6379

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always